name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Use a specific Flutter version or 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: ariane_app

      - name: Analyze code
        run: flutter analyze
        working-directory: ariane_app

      - name: Run tests
        run: flutter test
        working-directory: ariane_app

      - name: Build Windows application
        run: flutter build windows --release
        working-directory: ariane_app
